package com.myshop.api.enumeration;

public enum ItemType {
    TOP, OUTER, PANTS,
    ONEPIECE, SKIRT, SNEAKERS,
    SHOES, BAG, SPORTS,
    HEADWEAR, SOCKS_LEGWEAR, UNDERWEAR,
    EYEWEAR, ACCESSORY, WATCH,
    JEWELRY, BEAUTY, DIGITAL_TECH,
    LIFE, CULTURE, PET
}
