spring:
  profiles:
    active: prod, dev
    include: jwt, gcp, pay

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  cloud:
    gcp:
      credentials:
        location: classpath:myshop-373122-5a778e754845.json

server:
  servlet:
    encoding:
      charset: UTF-8

api:
  url:
    baseUrl: https://ae5f-210-100-160-190.jp.ngrok.io