spring:

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update # 테이블 생성 완료 후 none으로 변경
      use-new-id-generator-mappings: false
    open-in-view: false # true일 경우 영속성 컨텍스트가 트랜잭션 범위를 넘어선 레이어까지 살아있다.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb
        default_batch_fetch_size: 500
        format_sql: true

  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mysql-master:3306/myshop?serverTimezone=UTC&characterEncoding=UTF-8
      username: ENC(1FAdTLjUwRzFx2JhvWrBng==)
      password: ENC(Tl6cdxnStbOP5c0z+9LEYA==)
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mysql-slave:3306/myshop?serverTimezone=UTC&characterEncoding=UTF-8
      username: ENC(QG1Q/cDFhSbeex2+X44myw==)
      password: ENC(yQQhpb/2qYYBVm54ZEbWyA==)

jasypt:
  encryptor:
    password: enckey
    bean: jasyptStringEncryptor # Bean 이름
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

client:
  url: https://myshop.r-e.kr

api:
  url:
    baseUrl: https://api.myshop.r-e.kr